apiVersion: v1
kind: Secret
metadata:
  name: app-api-secret
type: Opaque
data:
  APP_KEY: YmFzZTY0OmFwTUFjRUgxNEw1b0pYd2o2ME4yREpmL2NMRlJPWkRwS1NlSU5HMHBiYUk9
  JWT_SECRET: dEdDWGI2ZWh1bWszenlVSTNCYXNGVGYzOFVyTm41RThETTFKNzZGU2IyVFF2WFVGY3Y2T3Y2NjJWbDRER2tLTw==