apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
  - port: {{ .Values.container.port }}
    name: postgres
  type: {{ .Values.service.type }}
  selector:
    app: postgres