replicaCount: 3

appImage:
  repository: timguardian/talklike
  pullPolicy: IfNotPresent
  tag: latest

proxyImage:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

appContainer:
  port: 9000
  volumeMountPath: /code/prod

proxyContainer:
  port: 80

codePersistence:
  storageClassName: standard
  storageCapacity: 1Gi
  hostPath: "/code/prod"
  reclaimPolicy: Delete

appConfig:
  name: TalkLike
  env: production
  debug: false
  url: http://talklike.kz
  timezone: UTC
  logChannel: stack
  dbConnection: pgsql
  dbPort: 5432
  cacheDriver: file
  queueConnection: sync

dbCredentials:
  type: Opaque
  database: dGFsa2xpa2UtcHJvZA== # talklike-prod
  username: YWRtaW4= # admin
  password: U3g5d3JySnlYbVQyNmdQNw== # Sx9wrrJyXmT26gP7

appCredentials:
  type: Opaque
  # base64:apMAcEH14L5oJXwj60N2DJf/cLFROZDpKSeING0pbaI=
  key: YmFzZTY0OmFwTUFjRUgxNEw1b0pYd2o2ME4yREpmL2NMRlJPWkRwS1NlSU5HMHBiYUk9
  # tGCXb6ehumk3zyUI3BasFTf38UrNn5E8DM1J76FSb2TQvXUFcv6Ov662Vl4DGkKO
  jwt: dEdDWGI2ZWh1bWszenlVSTNCYXNGVGYzOFVyTm41RThETTFKNzZGU2IyVFF2WFVGY3Y2T3Y2NjJWbDRER2tLTw==

service:
  type: NodePort
  port: 80
  targetPort: 80

dbChart:
  replicaCount: 1
  image:
    repository: postgres
    tag: 12
  container:
    mountPath: /var/lib/postgresql/prod/data
    port: 5432
  service:
    type: NodePort
  pv:
    name: postgres-pv-prod
    storage: "5Gi"
    reclaimPolicy: Retain
    hostPath: /var/prod/data
    storageClassName: standard
    labels:
      type: production
  credentials:
    db: dGFsa2xpa2UtcHJvZA== # talklike-prod
    user: YWRtaW4= # admin
    password: U3g5d3JySnlYbVQyNmdQNw== # Sx9wrrJyXmT26gP7
  nameOverride: "postgres-db-chart-production"
  fullnameOverride: "postgres-db-chart-production"


nameOverride: "talklike-api-production"
fullnameOverride: "talklike-api-production"


ingress:
  enabled: true
  host: talklike.kz