replicaCount: 2

appImage:
  repository: timguardian/talklike
  pullPolicy: Always
  tag: latest

proxyImage:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

appContainer:
  port: 9000
  volumeMountPath: /code/qa

proxyContainer:
  port: 80

codePersistence:
  storageClassName: standard
  storageCapacity: 1Gi
  hostPath: "/code/qa"
  reclaimPolicy: Delete

appConfig:
  name: TalkLike
  env: qa
  debug: true
  url: http://talklike.kz
  timezone: UTC
  logChannel: stack
  dbConnection: pgsql
  dbPort: 5432
  cacheDriver: file
  queueConnection: sync

dbCredentials:
  type: Opaque
  database: dGFsa2xpa2UtcWE= # talklike-qa
  username: cWEtZW5naW5lZXI= # qa-engineer
  password: U3g5d3JySnlYbVQyNmdQNw== # Sx9wrrJyXmT26gP7

appCredentials:
  type: Opaque
  # base64:apMAcEH14L5oJXwj60N2DJf/cLFROZDpKSeING0pbaI=
  key: YmFzZTY0OmFwTUFjRUgxNEw1b0pYd2o2ME4yREpmL2NMRlJPWkRwS1NlSU5HMHBiYUk9
  # tGCXb6ehumk3zyUI3BasFTf38UrNn5E8DM1J76FSb2TQvXUFcv6Ov662Vl4DGkKO
  jwt: dEdDWGI2ZWh1bWszenlVSTNCYXNGVGYzOFVyTm41RThETTFKNzZGU2IyVFF2WFVGY3Y2T3Y2NjJWbDRER2tLTw==

service:
  type: NodePort
  port: 80
  targetPort: 80

dbChart:
  replicaCount: 1
  image:
    repository: postgres
    tag: 12
  container:
    mountPath: /var/lib/postgresql/qa/data
    port: 5432
  service:
    type: NodePort
  pv:
    name: postgres-pv-qa
    storage: "5Gi"
    reclaimPolicy: Retain
    hostPath: /var/qa/data
    storageClassName: standard
    labels:
      type: qa
  credentials:
    db: dGFsa2xpa2UtcWE= # talklike-qa
    user: cWEtZW5naW5lZXI= # qa-engineer
    password: U3g5d3JySnlYbVQyNmdQNw== # Sx9wrrJyXmT26gP7
  nameOverride: "postgres-db-chart-qa"
  fullnameOverride: "postgres-db-chart-qa"


nameOverride: "talklike-api-qa"
fullnameOverride: "talklike-api-qa"


ingress:
  enabled: true
  host: qa.talklike.kz