apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "app-chart.fullname" . }}-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ include "app-chart.fullname" . }}-api"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ include "app-chart.fullname" . }}-api"
    spec:
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: "{{ include "app-chart.fullname" . }}-code-pv-claim"
      - name: config
        configMap:
          name: "{{ include "app-chart.fullname" . }}-nginx-config"
          items:
          - key: config
            path: default.conf
      - name: logs
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: testing
        emptyDir: {}
      - name: sessions
        emptyDir: {}
      - name: views
        emptyDir: {}
      initContainers:
        - args:
            - /bin/bash
            - -c
            - (php artisan migrate --force || true) && (php artisan config:cache || true) && (php
              artisan route:cache || true) && (cp -rp /var/www {{ .Values.appContainer.volumeMountPath }})
          envFrom:
            - secretRef:
                name: "{{ include "app-chart.fullname" . }}-app-api-db-secret"
            - secretRef:
                name: "{{ include "app-chart.fullname" . }}-app-api-secret"
            - configMapRef:
                name: "{{ include "app-chart.fullname" . }}-app-api-config-map"
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          name: artisan
          volumeMounts:
            - mountPath: {{ .Values.appContainer.volumeMountPath }}
              name: code
      containers:
      - name: api
        image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
        envFrom:
        - secretRef:
            name: "{{ include "app-chart.fullname" . }}-app-api-db-secret"
        - secretRef:
            name: "{{ include "app-chart.fullname" . }}-app-api-secret"
        - configMapRef:
            name: "{{ include "app-chart.fullname" . }}-app-api-config-map"
        ports:
        - containerPort: {{ .Values.appContainer.port }}
        volumeMounts:
        - name: code
          mountPath: {{ .Values.appContainer.volumeMountPath }}
        - name: logs
          mountPath: "{{ .Values.appContainer.volumeMountPath }}/www/storage/logs/"
        - name: cache
          mountPath: "{{ .Values.appContainer.volumeMountPath }}/www/storage/framework/cache"
        - name: sessions
          mountPath: "{{ .Values.appContainer.volumeMountPath }}/www/storage/framework/sessions"
        - name: views
          mountPath: "{{ .Values.appContainer.volumeMountPath }}/www/storage/framework/views"
        - name: testing
          mountPath: "{{ .Values.appContainer.volumeMountPath }}/www/storage/framework/testing"
      - name: nginx
        image: "{{ .Values.proxyImage.repository }}:{{ .Values.proxyImage.tag }}"
        ports:
        - containerPort: {{ .Values.proxyContainer.port }}
        volumeMounts:
        - name: code
          mountPath: {{ .Values.appContainer.volumeMountPath }}
        - name: config
          mountPath: /etc/nginx/conf.d