apiVersion: v1
kind: Secret
metadata:
  name: app-api-db-secret
type: {{ .Values.dbCredentials.type }}
data:
  DB_DATABASE: {{ .Values.dbCredentials.database }}
  DB_USERNAME: {{ .Values.dbCredentials.username }}
  DB_PASSWORD: {{ .Values.dbCredentials.password }}