apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "app-chart.fullname" . }}-app-api-secret"
type: {{ .Values.appCredentials.type }}
data:
  APP_KEY: {{ .Values.appCredentials.key }}
  JWT_SECRET: {{ .Values.appCredentials.jwt }}