{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "app-chart.fullname" . }}-app-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: "{{ include "app-chart.fullname" . }}-api-service"
            servicePort: 80
{{- end }}