kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.pv.storageClassName }}
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pv.storage }}"