apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "app-chart.fullname" . }}-postgres-root-secret"
type: Opaque
data:
  POSTGRES_DB: {{ .Values.credentials.db }}
  POSTGRES_USER: {{ .Values.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.credentials.password }}